In [1]:
import pandas as pd
from preprocessing import preprocessamento, missing

pre = preprocessamento.Preprocessamento()

df1, df2, df3, df4, df5 = map(pre.ler_csv, ['imob1.csv', 'imob2.csv',
                                            'imob3.csv', 'imob4.csv',
                                            'imob5.csv'])

lista = [df1, df2, df3, df4, df5]

df3['banheiros'] = df3['suites']
df4['banheiros'] = df4['suites']

for l in lista:
    l.drop(columns='suites', inplace=True)

dataset = pre.concatenar_datasets([df1, df2, df3, df4, df5])
dataset = dataset.iloc[:, 2:]
dataset = pre.ajustar_texto(dataset)
dataset = pre.ajustar_nomes_bairros(dataset)

In [2]:
dataset

                  bairro  quartos  banheiros  garagens    area   valor
0              Ibituruna        3          0         0    0.00       0
1        Todos Os Santos        1          0         0   23.50       0
2              Belvedere        2          1         1   48.68       0
3           Monte Alegre        2          1         1   46.38       0
4        Todos Os Santos        3          3         0    0.00       0
5       Jardim Liberdade        3          2         1   85.54       0
6         Candida Camara        3          3         2    0.00       0
7               Planalto        2          1         1   48.00       0
8               Planalto        2          1         1   48.00       0
9        Todos Os Santos        3          2         0    0.00       0
10       Todos Os Santos        2          3         0    0.00       0
11       Todos Os Santos        3          2         0    0.00       0
12              Planalto        2          1         1    0.00   95000
13             Belvedere        2          1         1    0.00   98000
14             Belvedere        2          1         0   43.03  120000
15             Belvedere        2          1         1    0.00  120000
16       Jardim Panorama        2          1         0    0.00  125000
17                Centro        1          1         0    0.00  130000
18             Morrinhos        2          1         0   82.05  130000
19             Belvedere        2          1         1    0.00  130000
20           Santa Laura        2          2         2    0.00  135000
21            Alice Maia        3          1         1   66.10  135000
22           Santa Laura        2          2         2    0.00  135000
23            Sao Mateus        2          1         1    0.00  140000
24           Santa Laura        2          2         2    0.00  140000
25           Santa Laura        2          2         2    0.00  140000
26                Cintra        2          1         1   74.80  140000
27       Sao Judas Tadeu        2          1         2   43.73  147000
28       Sao Judas Tadeu        2          1         2   43.73  147000
29       Sao Judas Tadeu        2          1         2   43.73  147000
...                  ...      ...        ...       ...     ...     ...
1328           Ibituruna        3          2         2    0.00   10000
1329     Jardim Panorama        2          2         1   65.00  215000
1330            Sao Jose        4          3         1    0.00  285000
1331        Augusta Mota        3          1         2   90.00  320000
1332        Augusta Mota        3          1         2   90.00  340000
1333              Centro        4          5         2    0.00  750000
1334              Centro        3          1         1    0.00  300000
1335      Candida Camara        4          3         2  176.00  900000
1336              Centro        4          3         2    0.00  600000
1337            Planalto        2          1         1    0.00  140000
1338      Candida Camara        0          0         0    0.00       0
1339       Morada Do Sol        3          1         1    0.00  220000
1340              Centro        2          1         1   66.00  300000
1341              Centro        3          2         2    0.00  650000
1342              Centro        2          1         1    0.00  190000
1343    Jardim Primavera        2          1         1   74.00  120000
1344           Belvedere        2          1         1   43.00  130000
1345    Jardim Primavera        1          1         1   74.00  120000
1346                Melo        3          1         1    0.00  330000
1347  Cidade Santa Maria        3          1         2  122.00  550000
1348       Morada Do Sol        2          1         1   60.00  150000
1349                Melo        3          2         2    0.00       0
1350              Centro        3          1         1    0.00  230000
1351           Ibituruna        3          2         2    0.00  420000
1352              Centro        3          1         1    0.00  450000
1353           Ibituruna        2          2         2  115.00  390000
1354                Melo        3          1         2    0.00  640000
1355           Ibituruna        2          1         2   60.00  270000
1356           Ibituruna        3          1         2   83.00  300000
1357        Augusta Mota        2          1         1   85.00  300000

[1358 rows x 6 columns]

In [3]:
# dataset = dataset.iloc[:, 0:].values
x = dataset.iloc[:, 0:5].values
#colunas = [1, 2, 4, 5]
#dataset = missing.missing_values(dataset, colunas)
#x = dataset[:, 0:5]
#y = dataset[:, 5]

In [7]:
x = missing.missing_values(x, [1, 2, 4])

In [8]:
pd.DataFrame(x)

                       0        1        2  3        4
0              Ibituruna        3  1.52658  0  82.9927
1        Todos Os Santos        1  1.52658  0     23.5
2              Belvedere        2        1  1    48.68
3           Monte Alegre        2        1  1    46.38
4        Todos Os Santos        3        3  0  82.9927
5       Jardim Liberdade        3        2  1    85.54
6         Candida Camara        3        3  2  82.9927
7               Planalto        2        1  1       48
8               Planalto        2        1  1       48
9        Todos Os Santos        3        2  0  82.9927
10       Todos Os Santos        2        3  0  82.9927
11       Todos Os Santos        3        2  0  82.9927
12              Planalto        2        1  1  82.9927
13             Belvedere        2        1  1  82.9927
14             Belvedere        2        1  0    43.03
15             Belvedere        2        1  1  82.9927
16       Jardim Panorama        2        1  0  82.9927
17                Centro        1        1  0  82.9927
18             Morrinhos        2        1  0    82.05
19             Belvedere        2        1  1  82.9927
20           Santa Laura        2        2  2  82.9927
21            Alice Maia        3        1  1     66.1
22           Santa Laura        2        2  2  82.9927
23            Sao Mateus        2        1  1  82.9927
24           Santa Laura        2        2  2  82.9927
25           Santa Laura        2        2  2  82.9927
26                Cintra        2        1  1     74.8
27       Sao Judas Tadeu        2        1  2    43.73
28       Sao Judas Tadeu        2        1  2    43.73
29       Sao Judas Tadeu        2        1  2    43.73
...                  ...      ...      ... ..      ...
1328           Ibituruna        3        2  2  82.9927
1329     Jardim Panorama        2        2  1       65
1330            Sao Jose        4        3  1  82.9927
1331        Augusta Mota        3        1  2       90
1332        Augusta Mota        3        1  2       90
1333              Centro        4        5  2  82.9927
1334              Centro        3        1  1  82.9927
1335      Candida Camara        4        3  2      176
1336              Centro        4        3  2  82.9927
1337            Planalto        2        1  1  82.9927
1338      Candida Camara  2.66298  1.52658  0  82.9927
1339       Morada Do Sol        3        1  1  82.9927
1340              Centro        2        1  1       66
1341              Centro        3        2  2  82.9927
1342              Centro        2        1  1  82.9927
1343    Jardim Primavera        2        1  1       74
1344           Belvedere        2        1  1       43
1345    Jardim Primavera        1        1  1       74
1346                Melo        3        1  1  82.9927
1347  Cidade Santa Maria        3        1  2      122
1348       Morada Do Sol        2        1  1       60
1349                Melo        3        2  2  82.9927
1350              Centro        3        1  1  82.9927
1351           Ibituruna        3        2  2  82.9927
1352              Centro        3        1  1  82.9927
1353           Ibituruna        2        2  2      115
1354                Melo        3        1  2  82.9927
1355           Ibituruna        2        1  2       60
1356           Ibituruna        3        1  2       83
1357        Augusta Mota        2        1  1       85

[1358 rows x 5 columns]

In [9]:
y = dataset.iloc[:, 5].values

In [15]:
y = missing.missing_values(y, [0])

IndexError: too many indices for array

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label = LabelEncoder()
x[:, 0] = label.fit_transform(x[:, 0])
onehot = OneHotEncoder(categorical_features=[0])
x = onehot.fit_transform(x).toarray()
x = x[:, 1:]

In [ ]:
pd.DataFrame(x)

In [ ]:
import statsmodels.formula.api as sm
import numpy as np
x = np.append(arr=np.ones((1358, 1)).astype(int), values=x, axis=1)
lista = list(range(0, 50))
x_opt = x[:, lista]

In [ ]:
pd.DataFrame(x_opt)

In [ ]:
ols = sm.OLS(endog=y, exog=x_opt).fit()

In [ ]:
ols.summary()